Downgrade Gradle in sample project because of removed outdated API (details below), assuming Kotlin 1.7 to 1.8 bump is not wanted yet.
* What went wrong:
Failed to notify task execution graph listener.
> org.gradle.api.reporting.DirectoryReport.setEnabled(Z)V

Caused by: java.lang.NoSuchMethodError: org.gradle.api.reporting.DirectoryReport.setEnabled(Z)V
        at org.jetbrains.kotlin.gradle.testing.internal.KotlinTestReport.disableTestReporting(KotlinTestReport.kt:242)

https://github.com/JetBrains/kotlin/blob/v1.7.0/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/testing/internal/KotlinTestReport.kt#L242

Gradle 8.0 removed that deprecated property:
https://docs.gradle.org/current/userguide/upgrading_version_7.html#report_and_testreport_api_cleanup

Fixed in Kotlin 1.8.0: https://github.com/JetBrains/kotlin/commit/e902ae7c09639559ac734842ebe5c383ec6e6e14

Deprecation warnings in sample project are all related to this, run: `sample$ gradlew build --warning-mode=all` for more info.